# Importar un fichero para pasarlo a un modelo

In [2]:
# Importaciones
import pandas as pd

In [7]:
nombre_fichero = "../importaciones/modelo_de_ingreso.csv"
nombre_modelo = "modelo_de_ingreso"
# abrir el archivo nombre_fichero y convertirlo en un panda dataset
df = pd.read_csv(nombre_fichero, sep=';', encoding='utf-8', on_bad_lines="warn")

# mostrar df
df

,id_alumno,Edad,Género,Plataforma Preferida,Nota media de acceso,Asiste a clase
0,1,18,Masculino,MacOS,9,Nunca
1,2,18,Masculino,MacOS,9,Nunca
2,3,20,Femenino,Windows,"7,9",Regularmente
3,4,20,Femenino,Windows,"7,9",Regularmente
4,5,19,Otro,Linux,10,Siempre
5,6,19,Otro,Linux,10,Siempre
6,7,22,Femenino,MacOS,6,Nunca
7,8,22,Femenino,MacOS,6,Nunca

In [ ]:
abrir la base de datos de sqlite3   
import sqlite3
conn = sqlite3.connect('../db.sqlite3')
c = conn.cursor()